/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateLogArgs } from "./CreateLogArgs";
import { UpdateLogArgs } from "./UpdateLogArgs";
import { DeleteLogArgs } from "./DeleteLogArgs";
import { LogFindManyArgs } from "./LogFindManyArgs";
import { LogFindUniqueArgs } from "./LogFindUniqueArgs";
import { Log } from "./Log";
import { LogService } from "../log.service";

@graphql.Resolver(() => Log)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class LogResolverBase {
  constructor(
    protected readonly service: LogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Log",
    action: "read",
    possession: "any",
  })
  async _logsMeta(
    @graphql.Args() args: LogFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Log])
  @nestAccessControl.UseRoles({
    resource: "Log",
    action: "read",
    possession: "any",
  })
  async logs(@graphql.Args() args: LogFindManyArgs): Promise<Log[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Log, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Log",
    action: "read",
    possession: "own",
  })
  async log(@graphql.Args() args: LogFindUniqueArgs): Promise<Log | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Log)
  @nestAccessControl.UseRoles({
    resource: "Log",
    action: "create",
    possession: "any",
  })
  async createLog(@graphql.Args() args: CreateLogArgs): Promise<Log> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Log)
  @nestAccessControl.UseRoles({
    resource: "Log",
    action: "update",
    possession: "any",
  })
  async updateLog(@graphql.Args() args: UpdateLogArgs): Promise<Log | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Log)
  @nestAccessControl.UseRoles({
    resource: "Log",
    action: "delete",
    possession: "any",
  })
  async deleteLog(@graphql.Args() args: DeleteLogArgs): Promise<Log | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
